### ISSUE TITLE
Logo op print Verhagen Groep aanpassen

### ISSUE THREAD

**Issue by ejmeulenkamp** [Meulenkamp/CA3#1]
Op afdrukken van de Verhagen Groep komt nu nog het logo van het Limburgs Landschap. Het logo van de Verhagen Groep staat in de map C:\HelpDeskCA3\Meulenkamp

Linda, zou jij dit aan kunnen passen?

**Comment by LindaVels** [comment]
Logo(.png)  is opgenomen in de configuratie voor verhagen groep  en wordt op de print getoond.
