### ISSUE TITLE
Logo print Overwater aanpassen

### ISSUE THREAD

**Issue by ejmeulenkamp** [Meulenkamp/CA3#2]
Op de afdrukken van Overwater Rentmeesterkantoor B.V. wordt het logo van het Limburgs Landschap afgedrukt. Het logo van Overwater staat in de map C:\HelpdeskCA3\Meulenkamp.

Linda: zou jij dit willen vervangen?

**Comment by LindaVels** [comment]
Logo(.png)  is opgenomen in de configuratie voor overwater en wordt op de print getoond.
