### ISSUE TITLE
Contractpercelen i.p.v. Afdelingen in de legenda

### ISSUE THREAD

**Issue by ejmeulenkamp** [Meulenkamp/CA3#3]
In de legenda wordt de kaartlaag 'Afdelingen' getoond. Dit zou 'Contractpercelen' moeten worden. Dit geldt ook voor als je op het plusje klikt, dan staat er weer 'Afdelingen' bij het gebruikte symbool. De tabel in de database moet 'afdelingen' blijven heten!

Linda: zou jij dit aan kunnen passen?

N.B.: In het venster Extra > Opties > Tabblad 'Giskoppelingen' zal dan waarschijnlijk ook 'Contractpercelen' in plaats van 'Afdelingen' moeten komen te staan in het veld 'kaartlaagnaam' bij de vensters 'Contractpercelen', 'Contracten' en 'Beheersubsidies'.

**Comment by LindaVels** [comment]
Ik heb de labels in de configuratie aangepast. de laagnaam blijft wel gelijk maar wordt nergens getoond. Het is niet nodig de gis-koppelingen aan te passen
